export enum EstadoFisico {
    NOVO = "NOVO",
    BOM_ESTADO = "BOM_ESTADO",
    USADO_LEVE = "USADO_LEVE",
    USADO_MODERADO = "USADO_MODERADO",
    DANIFICADO_LEVE = "DANIFICADO_LEVE",
    DANIFICADO_GRAVE = "DANIFICADO_GRAVE",
    INSERVIVEL = "INSERVIVEL"
}