export enum TipoEquipamento {
    COMPUTADOR_MESA = "COMPUTADOR_MESA",
    NOTEBOOK = "NOTEBOOK",
    MONITOR = "MONITOR",
    IMPRESSORA = "IMPRESSORA",
    SERVIDOR = "SERVIDOR",
    ROTEADOR = "ROTEADOR",
    CABO_ESTRUTURADO = "CABO_ESTRUTURADO",
    FONTE_ALIMENTACAO = "FONTE_ALIMENTACAO"
}